apiVersion: v2
name: pipe-calculation
description: A Helm chart for the pipe-calculation application
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - alias: frontend
    name: application
    version: "6.0.1"
    repository: https://stakater.github.io/stakater-charts
  - alias: api
    name: application
    version: "6.0.1"
    repository: https://stakater.github.io/stakater-charts
